[[manager.prepend_keymap]]
on = ["<l>"]
run = "plugin open_force"
desc = "open force"

[[manager.prepend_keymap]]
on = ["<S-l>"]
run = "plugin open_force --args='detatch'"
desc = "open detatch"

[[manager.prepend_keymap]]
on  = ["<k>"]
run = "plugin wrap --args=-1"

[[manager.prepend_keymap]]
on  = ["<j>"]
run = "plugin wrap --args=1"

[[manager.prepend_keymap]]
on  = ["<S-k>"]
run = "plugin wrap --args=-5"

[[manager.prepend_keymap]]
on  = ["<S-j>"]
run = "plugin wrap --args=5"

[[manager.prepend_keymap]]
on = ["<m>"]
run = "plugin toggle_layout --args='current'"
desc = "change layout"

[[manager.prepend_keymap]]
on = ["<p>"]
run = "plugin toggle_layout --args='preview'"
desc = "change layout"

[[manager.prepend_keymap]]
on = ["<n>"]
run = "create"
desc = "create file/folder"

[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[input.prepend_keymap]]
on   = ["<Esc>"]
run  = "close"
desc = "Cancel input"
