#!/usr/bin/env bash

TIMEFORMAT='%R'

result=$( { time timeout 16 curl -4 -o /dev/null http://bouygues.testdebit.info/10M.iso > /dev/null 2>&1; } 2>&1 | tr "," ".")

speed=$(awk "BEGIN {printf \"%.2f\", 8.0 * 10.0 / $result}")

if (( $(awk 'BEGIN {print ('$speed' > 1000.0) ? 1 : 0}') )); then
  echo "✘"
else
  echo "$speed Mb/s"
fi
