#!/usr/bin/env bash

server_status=$(curl -s https://api.mcsrvstat.us/3/mc.penwing.org)

num_players=$(echo "$server_status" | awk -F'"online":' '{print $2}' | awk -F',' '{print $1}')

if [ "$num_players" = "false}" ]; then 
	echo " ✘ "
	exit 0
fi
echo "$num_players "
